#rootウィジェット
TextWidget:

<MyLabel@Label>:
    canvas:
        Color:
            rgba: 1,0,0,1
        Line:
            width: 3
            rounded_rectangle:10,500,100,100,5
            #radius=[0, 50, 0, 50], source=TEXTURE
        Rectangle:
            pos: 10,500
            size: 100,100        

<MyButton@Button>:
    font_size: 68
     #Ellipse:
        #    pos: self.pos
        #    size: self.size

#<>の間にウィジェットクラスの名前としてクラスが宣言される場合、
#そのクラスの全てのインスタンスをグラフィカルに表現する方法を定義します。
<TextWidget>:
    #rows:2
    #cols:1
    #padding: 1.0
    #spacing: 1.0
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        #size_hint_y: None
        #height: self.minimum_height       
        #padding: 20,50,20, 10
        # ラベル
        FloatLayout:
            MyLabel:
                #size_hint: 0.9,0.1
                #pos_hint:{'x':0.05,'top': 0.99}
                #radius:50
                #pos:150,0.0
                #padding_x: 20
                #pos: 10, 700
                bold: True
                #text_size: (10, 10)
                #text_size: self.size
                halign: 'right'
                valign: 'middle'
                multiline:True
                #background_color:1,50,0,1  
                #canvas.before:
                #    Color:
                #        rgba: 0.8, 0.5, 0.5, 1.0
                #    Rectangle:
                        #pos: 10,500
                        #size: 100,100
               
                id: label1
                #markup: True
                font_size: 30
                text: 'root.text'
                color: 1,1,1,1
              
            Label:
                id: label1
                font_size: 30#
                text: "label1 root.text"
                color: 1,1,0,1#text color
                size_hint: 0.8,0.2#
                pos_hint:{'x':0.1, 'top':.88}#
                canvas:
                    Color:
                        rgba: 1, 0.5, 0.5, 1.0# line to color
                    #Rectangle:
                    #    pos: self.pos
                    #    size: self.size
                    Line:
                        rectangle: (self.x+30, self.y+100, self.width-50, self.height-200)
                        
                        #width: 3
                        #rounded_rectangle:0.1,800,100,100,5
                        #radius=[0, 50, 0, 50], source=TEXTURE
                    Rectangle:
                        #pos: self.x+30, self.y+100
                        #size: self.width-50, self.height-200      
                        #pos:70, 750
                          
        
            Label:
                size_hint: 0.8,0.2
                pos_hint:{'x':0.1, 'y':0.46}
                canvas.before:
                    Color:
                        rgba: 0.5, 0.5, 0.5, 1.0
                    Rectangle:
                        pos: self.pos
                        size: self.size
                
                #pos:70, 600
                id: label1
                font_size: 68
                text: root.text
                color: root.color        
   
        ScrollView:
            GridLayout:
                cols:1
                size_hint_y: None
                row_default_height: 20
                height: self.minimum_height
                Button:
                    text: "1"
                Button:
                    text: "2"
               
               
           
        BoxLayout:
            size_hint_y: None
            #height: self.minimum_height
            #orientation: 'vertical'
            #size_hint_y: 0.1
            #padding: 20,30,20, 10
            Button:
                
                id: button1
                text: "Up"
                font_size: 68
                on_press: root.buttonClicked()

            Button:
                id: button2
                text: "Mid"
                font_size: 68
                on_press: root.buttonClicked2()

            Button:
                id: button3
                text: "Down"
                font_size: 68
                on_press: root.buttonClicked3()
