MainScreen: # ルートに追加

<MainScreen>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        # ラベル
        Label:
            id: label1
            font_size: 15
            text: root.text    # root(MainScreen)の変数テキストの値を取得
            #color: root.color

        Button:
            id: button1
            text: "OK"
            font_size: 68
            on_press: root.buttonClicked()  # ボタンをクリックした時にpython側の関数を呼ぶ

        Button:
            id: button2
            text: "GetUrl"
            font_size: 68
            on_press: root.geturlClicked()  # ボタンをクリックした時にpython側の関数を呼ぶ    