TextWidget:

<TextWidget>:
    canvas.after:
        Color:
            rgba: 1, 1, 1, 1
        Line:
            rectangle: self.x+1,self.y+1,self.width-1,self.height-1
            dash_offset: 5
            dash_length: 3
    #rows:2
    #cols:1
    #padding: 1.0
    #spacing: 1.0
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        #size_hint_y: None
        #height: self.minimum_height       
        #padding: 20,50,20, 10
        # ラベル
        FloatLayout:
            #pos_hint:{'top': 0.5}
            #size:30,30
            #size_hint_y: 0.3
            Label:
                size_hint: 0.9,0.1
                pos_hint:{'x':0.05,'top': 0.99}
                background_normal: 'normal.png'
                background_down: 'down.png'
                border: 30,30,30,30
                #pos:150,0.0
                #padding_x: 20
                #pos: 10, 700
                bold: True
                text_size: self.size
                halign: 'right'
                valign: 'middle'
                multiline:True
                #background_color:1,50,0,1  
                canvas.before:
                    Color:
                        rgba: 0.8, 0.5, 0.5, 1.0
                    Rectangle:
                        pos: self.pos
                        size: self.size
               
                id: label1
                #markup: True
                #font_size: 6
                text: 'root.text'
                color: root.color

            Label:
                size_hint: 0.8,0.2
                pos_hint:{'x':0.1, 'top':.88}
                canvas.before:
                    Color:
                        rgba: 0.5, 0.5, 0.5, 1.0
                    Rectangle:
                        pos: self.pos
                        size: self.size
                
                #pos:70, 750
                id: label1
                font_size: 68
                text: root.text
                color: root.color    
        
            Label:
                size_hint: 0.8,0.2
                pos_hint:{'x':0.1, 'y':0.46}
                canvas.before:
                    Color:
                        rgba: 0.5, 0.5, 0.5, 1.0
                    Rectangle:
                        pos: self.pos
                        size: self.size
                
                #pos:70, 600
                id: label1
                font_size: 68
                text: root.text
                color: root.color        
   
        ScrollView:
            GridLayout:
                cols:1
                size_hint_y: None
                row_default_height: 200
                height: self.minimum_height
                Button:
                    text: "1"
                Button:
                    text: "2"
                Button:
                    text: "3"
                Button:
                    text: "4"
                Button:
                    text: "5"
                Button:
                    text: "6"
                Button:
                    text: "7"
                Button:
                    text: "8"
                Button:
                    text: "9"
                Button:
                    text: "10"
                Button:
                    text: "11"
                Button:
                    text: "12"
           
        BoxLayout:
            size_hint_y: None
            #height: self.minimum_height
            #orientation: 'vertical'
            #size_hint_y: 0.1
            #padding: 20,30,20, 10
            Button:
                markup: True
                background_normal: 'normal.png'
                background_down: 'down.png'
                border: 100,100,100,100
                id: button1
                text: "Up"
                font_size: 68
                on_press: root.buttonClicked()

            Button:
                id: button2
                text: "Mid"
                font_size: 68
                on_press: root.buttonClicked2()

            Button:
                id: button3
                text: "Down"
                font_size: 68
                on_press: root.buttonClicked3()
